---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: post-postgresql-db
spec:
  serviceName: post-postgresql-db-service
  selector:
    matchLabels:
      app: post-postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: post-postgresql-db
    spec:
      volumes:
        - name: post-postgresql-db-config
          configMap:
            name: post-postgresql-db-config
      containers:
        - name: post-postgresql-db
          image: postgres:15-alpine3.17
          volumeMounts:
            - name: post-postgresql-db-disk
              mountPath: /var/lib/postgresql/data

            - mountPath: /docker-entrypoint-initdb.d
              name: post-postgresql-db-config
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: post-postgresql-db-config
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-name
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-user
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-password
                  optional: false
          startupProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 20
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 20
            terminationGracePeriodSeconds: 5
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: post-postgresql-db-disk
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: post-postgres
spec:
  selector:
    app: post-postgresql-db
  type: ClusterIP
  ports:
    - port: 15432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8s-program
  name: post-postgresql-db-config
  labels:
    app: post-postgresql-db
data:
  PGDATA: /data/pgdata
  init.sql: |
    create table if not exists post
    (
        id        integer not null
            primary key
            constraint post_id_check
                check (id >= 1),
        author_id integer not null
            constraint post_author_id_check
                check (author_id >= 1),
        posted_at date,
        "text"    varchar(255)
    );

    insert into post(id, author_id, posted_at, "text")
    values (2, 10, '04-01-1987', 'Hooray!, 1 year'),
           (3, 10, '04-01-1988', 'Hooray!, 2 year'),
           (4, 10, '04-01-1989', 'Hooray!, 3 year'),
           (5, 10, '04-01-1990', 'Hooray!, 4 year'),
           (6, 10, '04-01-1991', 'Hooray!, 5 year'),
           (7, 10, '04-01-1992', 'Hooray!, 6 year'),
           (8, 10, '04-01-1993', 'Hooray!, 7 year'),
           (9, 10, '04-01-1993', 'Hooray!, 8 year'),
           (10, 10, '04-01-1993', 'Hooray!, 9 year'),
           (11, 10, '04-01-1993', 'Hooray!, 10 year'),
           (12, 20, '04-01-1987', 'Hooray!, 1 year'),
           (13, 20, '04-01-1988', 'Hooray!, 2 year'),
           (14, 20, '04-01-1989', 'Hooray!, 3 year'),
           (15, 20, '04-01-1990', 'Hooray!, 4 year'),
           (16, 20, '04-01-1991', 'Hooray!, 5 year'),
           (17, 20, '04-01-1992', 'Hooray!, 6 year'),
           (18, 20, '04-01-1993', 'Hooray!, 7 year'),
           (22, 30, '04-01-1987', 'Hooray!, 1 year'),
           (23, 30, '04-01-1988', 'Hooray!, 2 year'),
           (24, 30, '04-01-1989', 'Hooray!, 3 year'),
           (25, 30, '04-01-1990', 'Hooray!, 4 year'),
           (26, 30, '04-01-1991', 'Hooray!, 5 year'),
           (27, 30, '04-01-1992', 'Hooray!, 6 year'),
           (28, 30, '04-01-1993', 'Hooray!, 7 year');


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: user-postgresql-db
spec:
  serviceName: user-postgresql-db-service
  selector:
    matchLabels:
      app: user-postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: user-postgresql-db
    spec:
      volumes:
        - name: user-postgresql-db-config
          configMap:
            name: user-postgresql-db-config
      containers:
        - name: user-postgresql-db
          image: postgres:15-alpine3.17
          volumeMounts:
            - name: user-postgresql-db-disk
              mountPath: /var/lib/postgresql/data

            - mountPath: /docker-entrypoint-initdb.d
              name: user-postgresql-db-config
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: user-postgresql-db-config
            - secretRef:
                name: user-postgresql-db-secret
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"
            initialDelaySeconds: 20
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 20
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}"
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 20
            terminationGracePeriodSeconds: 2
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: user-postgresql-db-disk
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: user-postgres
spec:
  selector:
    app: user-postgresql-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: k8s-program
  name: user-postgresql-db-config
  labels:
    app: user-postgresql-db
data:
  PGDATA: /data/pgdata
  init.sql: |
    create table if not exists users
    (
        id              integer           not null
            primary key
            constraint users_id_check
                check (id >= 1),
        amount_of_posts integer default 0 not null,
        username        varchar(255)      not null
    );

    insert into users(id, amount_of_posts, username)
    values (10, 10, 'Sergei'),
           (20, 20, 'Evgenii'),
           (30, 30, 'Slava');