---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-program
  name: user-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/Temp/user/data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-program
  name: user-pv-claim
  labels:
    app: user
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi