---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---
apiVersion: v1
kind: Secret
metadata:
  namespace: k8s-program
  name: post-postgresql-db-secret
  labels:
    app: post-postgresql-db
data:
  post-db-name: cG9zdHM=
  post-db-user: amRiY19wb3N0
  post-db-password: cGFzc3cwcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  namespace: k8s-program
  name: user-postgresql-db-secret
  labels:
    app: user-postgresql-db
data:
  POSTGRES_DB: dXNlcnM=
  POSTGRES_USER: amRiY191c2Vy
  POSTGRES_PASSWORD: cGFzc3cwcmQ=
