---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program
---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: post-service
spec:
  ports:
    - protocol: "TCP"
      port: 18081
      targetPort: 18081
      nodePort: 18081
  selector:
    app: post
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: post
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - image: epamviachaslaurakhmanko/post-service:1.0.0
          imagePullPolicy: Always
          name: post
          ports:
            - containerPort: 18081
          env:
            - name: DbPassword
              value: passw0rd
            - name: DbUserHost
              value: post-postgres
            - name: DbUser
              value: jdbc_post
            - name: UserHostName
              value: user-service

---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: user-service
spec:
  ports:
    - protocol: "TCP"
      port: 18080
      targetPort: 18080
      nodePort: 18080
  selector:
    app: user
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: user
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      volumes:
        - name: user-pv-storage
          persistentVolumeClaim:
            claimName: user-pv-claim
      containers:
        - image: epamviachaslaurakhmanko/user-service:1.0.0
          imagePullPolicy: Always
          name: user
          ports:
            - containerPort: 18080
          env:
            - name: DbPassword
              value: passw0rd
            - name: DbUserHost
              value: user-postgres
            - name: DbUser
              value: jdbc_user
          volumeMounts:
            - mountPath: "/usr/share"
              name: user-pv-storage