server:
  port: 18081

spring:
  mvc:
    format:
      date: dd-MM-yyyy
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DbUserHost:localhost}:${DbPort:15432}/${DbName:posts}
    username: ${DbUser:jdbc_post}
    password: ${DbPassword:passw0rd}
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

clients:
  codecs:
    max-memory-size: 31457280
  timeout: 1000
  service:
    users:
      baseurl: http://${UserHostName:localhost}:18080/users/

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true