---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: post-postgresql-db-secret
  labels:
    app: post-postgresql-db
data:
  post-db-name: cG9zdHM=
  post-db-user: amRiY19wb3N0
  post-db-password: cGFzc3cwcmQ=
