---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: post-service
spec:
  ports:
    - protocol: "TCP"
      port: 18081
      targetPort: 18081
      nodePort: 30081
  selector:
    app: post
  type: NodePort