---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: post
  labels:
    {{- include "k8s-docker-microservice.labels" . | nindent 4 }}
    application: posts
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      pod-name: post-service
  template:
    metadata:
      labels:
        pod-name: post-service
        app: post
    spec:
      containers:
        - name: post-service
          image: epamviachaslaurakhmanko/post-service:1.1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 18081
          env:
            - name: DbUserHost
              value: post-postgres
            - name: DbUser
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-user
                  optional: false
            - name: DbPassword
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-password
                  optional: false
            - name: UserHostName
              value: user-service
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 1
            failureThreshold: 120
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http