---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: post
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - image: epamviachaslaurakhmanko/post-service:1.1.0
          imagePullPolicy: Always
          name: post
          ports:
            - containerPort: 18081
          env:
            - name: DbUserHost
              value: post-postgres
            - name: DbUser
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-user
                  optional: false
            - name: DbPassword
              valueFrom:
                secretKeyRef:
                  name: post-postgresql-db-secret
                  key: post-db-password
                  optional: false
            - name: UserHostName
              value: user-service
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 18081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 18081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 18081
            terminationGracePeriodSeconds: 2