---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: post-service
  labels:
    {{- include "k8s-docker-microservice.labels" . | nindent 4 }}
    application: posts
spec:
  ports:
    - name: http
      protocol: TCP
      port: 18081
      targetPort: http
  selector:
    pod-name: post-service