---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: post-service
spec:
  ports:
    - protocol: "TCP"
      port: 18081
      targetPort: 18081
      nodePort: 30081
  selector:
    app: post
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: user-service
spec:
  ports:
    - protocol: "TCP"
      port: 18080
      targetPort: 18080
      nodePort: 30080
  selector:
    app: user
  type: NodePort