---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: user-postgresql-db-secret
  labels:
    application: users
data:
  POSTGRES_DB: dXNlcnM=
  POSTGRES_USER: amRiY191c2Vy
  POSTGRES_PASSWORD: cGFzc3cwcmQ=
