---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: user
  labels:
    {{- include "k8s-docker-microservice.labels" . | nindent 4 }}
    application: users
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      pod-name: user-service
  template:
    metadata:
      labels:
        pod-name: user-service
        application: users
    spec:
      volumes:
        - name: user-pv-storage
          persistentVolumeClaim:
            claimName: user-pv-claim
      containers:
        - name: user-service
          image: epamviachaslaurakhmanko/user-service:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 18080
          env:
            - name: DbPassword
              valueFrom:
                secretKeyRef:
                  name: user-postgresql-db-secret
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: DbUserHost
              value: user-postgres
            - name: DbUser
              valueFrom:
                secretKeyRef:
                  name: user-postgresql-db-secret
                  key: POSTGRES_USER
                  optional: false
          volumeMounts:
            - mountPath: "/usr/share"
              name: user-pv-storage
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
            periodSeconds: 1
            failureThreshold: 120
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
