---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: user-pv-claim
  labels:
    application: users
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi