---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ template "k8s-docker-microservice.namespace" . }}
  name: user-pv
  labels:
    application: users
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/Temp/user/data/"