---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: post-postgresql-db-secret
  labels:
    app: post-postgresql-db
data:
  post-db-name: cG9zdHM=
  post-db-user: amRiY19wb3N0
  post-db-password: cGFzc3cwcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: user-postgresql-db-secret
  labels:
    app: user-postgresql-db
data:
  POSTGRES_DB: dXNlcnM=
  POSTGRES_USER: amRiY191c2Vy
  POSTGRES_PASSWORD: cGFzc3cwcmQ=
